version: '3'

services:
  todo_postgres:
    image: postgres:11
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=passwd
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web_app:
    build: .
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:passwd@db/postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/todo_service
    depends_on:
      - todo_postgres